# Generated by Django 3.2.19 on 2023-06-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_saver_appointment', '0002_remove_appointment_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
