# Generated by Django 3.2.19 on 2023-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_saver_appointment', '0003_auto_20230622_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
