# Generated by Django 3.2.19 on 2023-06-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_saver_appointment', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
