# Generated by Django 3.2.19 on 2023-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_saver_user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
