# Generated by Django 3.2.19 on 2023-06-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('life_saver_user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='life_saver_user_auth.user')),
                ('specialization', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('qualification', models.CharField(max_length=30)),
                ('fees', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
